services:
  nginx:
    image: registry.cn-heyuan.aliyuncs.com/llm-good/nginx:${VERSION}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/${NGINX_CONF:-default.conf}:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - frontend
      - backend
      - website
      - game-hub
      - certbot
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always

  website:
    image: registry.cn-heyuan.aliyuncs.com/llm-good/website:${VERSION}
    expose:
      - 80
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    restart: always

  frontend:
    image: registry.cn-heyuan.aliyuncs.com/llm-good/frontend:${VERSION}
    expose:
      - 80
    environment:
      - VITE_API_URL=/api
    depends_on:
      - backend
    restart: always

  backend:
    image: registry.cn-heyuan.aliyuncs.com/llm-good/backend:${VERSION}
    expose:
      - ${BACKEND_PORT:-3000}
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: registry.cn-heyuan.aliyuncs.com/llm-good/db:${VERSION}
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./apps/backend/prisma/init.sh:/docker-entrypoint-initdb.d/init.sh
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  game-hub:
    image: registry.cn-heyuan.aliyuncs.com/llm-good/game-hub:${VERSION}
    expose:
      - 80
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    restart: always

volumes:
  mysql_data: 