version: 2

# Storybook 配置
storybook:
  # 全局参数配置
  args: {}
  globals: {}
  queryParams: {}

# 快照配置
snapshot:
  widths: [375, 768, 1280]
  min-height: 800
  enableJavaScript: true
  percy-css: |
    canvas {
      animation: none !important;
      transition: none !important;
      will-change: auto !important;
    }
    * {
      animation: none !important;
      transition: none !important;
    }

# 资源发现配置
discovery:
  allowedHostnames: ['localhost']
  disableCache: true
  networkIdleTimeout: 750